### ISSUE TITLE
can't install FDRreg

### ISSUE THREAD

**Issue by bling1000** [jgscott/FDRreg#7]
Hi, I tried to install FDRreg v0.2 using devtools::install_github('jgscott/FDRreg', subdir="R_pkg/"), but I got the following error. 

Error: HTTP error 404.
  Not Found

  Did you spell the repo owner (`jgscott`) and repo name (`FDRreg`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

Thanks!
Ling

**Comment by oyyleung** [comment]
got the same error, but this works:
install_github('jgscott/FDRreg/R_pkg')
